server:
  port: 8081 #设置端口号
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html  #跳到html
    static-path-pattern: /static/**  #配置静态资源 ，如果不手动配置，系统默认位置"classpath:/META-INF/resources/","classpath:/resources/", "classpath:/static/", "classpath:/public/"
    format:
      date: yyyy-MM-dd #系统的接收时间格式，如果不一样，则不可以接收。默认dd/MM/yyyy，可以改为自己的格式如yyyy-MM-dd
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效 --对jsp有用，html没有产生作用
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///testdb?serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false  #关闭thymeleaf缓存
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: false  #是否显示sql语句
    properties:
      hibernate:
        format_sql: true # 格式化sql

